/* Pin and connection recovery.

   UEdGraphPin stopped being a UObject in UE 4.16; pins are written by the owning
   node after its tagged properties, and every pin reference on disk is the pair
   (owning node FPackageIndex, pin FGuid). Each pin record starts with that pair
   repeated twice for the pin itself, which makes an unambiguous marker to scan for.

   Layout after the marker (offsets confirmed against UE 5.6 assets):
     +0   FPackageIndex owner, FGuid PinId      (self reference)
     +20  FPackageIndex owner, FGuid PinId      (repeated)
     +40  FName  PinName
     +48  FText  PinFriendlyName, FString PinToolTip, uint8 Direction
     ...  FName  PinCategory, FName PinSubCategory, FPackageIndex PinSubCategoryObject
     ...  FString DefaultValue, FString AutogeneratedDefaultValue
     ...  pin references for LinkedTo / SubPins / ParentPin

   Variable-length fields sit between the fixed ones, so PinCategory is located by
   scanning for a known category name and the default-value offset is calibrated
   against the whole file rather than hard-coded. */
(function (global) {
  'use strict';
  var UA = global.UA;

  var CATEGORIES = {
    exec: 1, bool: 1, byte: 1, int: 1, int64: 1, float: 1, double: 1, real: 1,
    name: 1, delegate: 1, mcdelegate: 1, object: 1, interface: 1, string: 1,
    text: 1, struct: 1, class: 1, softobject: 1, softclass: 1, wildcard: 1,
    enum: 1, fieldpath: 1, asset: 1, assetclass: 1, optional: 1
  };
  UA.PIN_CATEGORIES = CATEGORIES;

  function isNodeClass(name) {
    if (!name) return false;
    return /^(K2Node_|EdGraphNode_|AnimGraphNode_|MaterialGraphNode|NiagaraNode|SoundCueGraphNode|BehaviorTreeGraphNode|EnvironmentQueryGraphNode|ControlRigGraphNode|MetasoundEditorGraphNode|PCGEditorGraphNode|EdGraphNode$)/.test(name);
  }
  UA.isNodeClass = isNodeClass;

  /* ------------------------------------------------------------- utilities */

  function looksLikeGuid(u8, off) {
    for (var i = 0; i < 16; i++) if (u8[off + i] !== 0) return true;
    return false;
  }
  function sameBytes(u8, a, b, n) {
    for (var i = 0; i < n; i++) if (u8[a + i] !== u8[b + i]) return false;
    return true;
  }
  function hexAt(u8, off) {
    var s = '';
    for (var i = 0; i < 16; i++) s += (u8[off + i] < 16 ? '0' : '') + u8[off + i].toString(16);
    return s;
  }

  /* Read an FString without a Reader; returns null when it does not look like one.
     `empty` reflects the decoded text, not the raw length: a string holding only
     its null terminator is empty too, and treating it otherwise makes junk
     offsets look like real default values during calibration. */
  function tryString(dv, u8, off, limit, allowEmpty) {
    if (off + 4 > limit) return null;
    var n = dv.getInt32(off, true);
    if (n === 0) return allowEmpty ? { text: '', end: off + 4, empty: true } : null;
    if (n > 0) {
      if (n > 4096 || off + 4 + n > limit) return null;
      if (u8[off + 4 + n - 1] !== 0) return null;
      var s = '';
      for (var i = 0; i < n - 1; i++) {
        var c = u8[off + 4 + i];
        if (c < 9 || (c > 13 && c < 32)) return null;
        s += String.fromCharCode(c);
      }
      if (!s && !allowEmpty) return null;
      return { text: s, end: off + 4 + n, empty: s.length === 0 };
    }
    var chars = -n;
    if (chars > 4096 || off + 4 + chars * 2 > limit) return null;
    var t = '';
    for (var j = 0; j < chars - 1; j++) {
      var cc = dv.getUint16(off + 4 + j * 2, true);
      if (cc < 9 || (cc > 13 && cc < 32)) return null;
      t += String.fromCharCode(cc);
    }
    if (!t && !allowEmpty) return null;
    return { text: t, end: off + 4 + chars * 2, empty: t.length === 0 };
  }

  /* ----------------------------------------------------------- pin scanning */

  /**
   * Locate pin records in one node's trailing bytes.
   * @returns {{pins: Array, mode: string}}
   */
  function scanNodePins(pkg, view, selfIndex) {
    var dv = view.dv, u8 = view.u8, start = view.start, end = view.end;
    var nameCount = pkg.names.length;
    var heads = [], mode = 'paired';

    /* Strict marker: the self reference written twice back to back. */
    for (var a = start; a + 48 <= end; ) {
      if (dv.getInt32(a, true) === selfIndex && dv.getInt32(a + 20, true) === selfIndex &&
          looksLikeGuid(u8, a + 4) && sameBytes(u8, a + 4, a + 24, 16)) {
        heads.push({ at: a, nameAt: a + 40, bodyAt: a + 48 });
        a += 48;
      } else a++;
    }

    /* Fallback for engine versions that write the reference once. */
    if (!heads.length) {
      mode = 'single';
      for (var b = start; b + 28 <= end; ) {
        if (dv.getInt32(b, true) === selfIndex && looksLikeGuid(u8, b + 4)) {
          var ni = dv.getInt32(b + 20, true), nn = dv.getInt32(b + 24, true);
          if (ni >= 0 && ni < nameCount && nn >= 0 && nn < 4096) {
            heads.push({ at: b, nameAt: b + 20, bodyAt: b + 28 });
            b += 28;
            continue;
          }
        }
        b++;
      }
    }
    if (!heads.length) return { pins: [], mode: 'none' };

    var pins = [];
    for (var i = 0; i < heads.length; i++) {
      var h = heads[i];
      var segEnd = (i + 1 < heads.length) ? heads[i + 1].at : end;
      var pin = {
        guid: hexAt(u8, h.at + 4),
        headerAt: h.at,
        bodyAt: h.bodyAt,
        segEnd: segEnd,
        name: '',
        category: null,
        subCategory: null,
        subCategoryObject: null,
        direction: null,
        defaultValue: null,
        links: [],
        subPinOf: null
      };
      var ni2 = dv.getInt32(h.nameAt, true), nn2 = dv.getInt32(h.nameAt + 4, true);
      if (ni2 >= 0 && ni2 < nameCount && nn2 >= 0 && nn2 < 65536) pin.name = pkg.name(ni2, nn2);
      else {
        var s = tryString(dv, u8, h.nameAt, segEnd, false);   /* pre-4.19 wrote FString names */
        if (s) pin.name = s.text;
      }

      /* PinCategory: first known category name inside this pin's slice. */
      for (var c = h.bodyAt; c + 8 <= segEnd; c++) {
        var ci = dv.getInt32(c, true);
        if (ci < 0 || ci >= nameCount) continue;
        if (dv.getInt32(c + 4, true) !== 0) continue;
        var nm = pkg.names[ci];
        if (!nm || !CATEGORIES[nm.toLowerCase()]) continue;
        pin.category = nm;
        pin.categoryAt = c;
        var si = dv.getInt32(c + 8, true), sn = dv.getInt32(c + 12, true);
        if (si >= 0 && si < nameCount && sn >= 0 && sn < 65536) {
          var sub = pkg.name(si, sn);
          pin.subCategory = sub === 'None' ? null : sub;
        }
        var so = dv.getInt32(c + 16, true);
        if (so && so >= -pkg.imports.length && so <= pkg.exports.length) {
          pin.subCategoryObject = pkg.indexName(so);
        }
        break;
      }
      pins.push(pin);
    }
    return { pins: pins, mode: mode };
  }

  /* Direction is the byte immediately before PinCategory in every version seen,
     but confirm it against the file instead of assuming. */
  function calibrateDirection(nodes) {
    var offsets = [-1, -4];
    var best = { off: -1, score: -1 };
    for (var o = 0; o < offsets.length; o++) {
      var good = 0, total = 0;
      for (var n = 0; n < nodes.length; n++) {
        var nd = nodes[n];
        for (var p = 0; p < nd.pins.length; p++) {
          var pin = nd.pins[p];
          if (pin.categoryAt == null) continue;
          total++;
          var at = pin.categoryAt + offsets[o];
          if (at < nd.view.start) continue;
          var v = offsets[o] === -1 ? nd.view.u8[at] : nd.view.dv.getInt32(at, true);
          if (v === 0 || v === 1) good++;
        }
      }
      var score = total ? good / total : 0;
      if (score > best.score) best = { off: offsets[o], score: score, total: total };
    }
    return best;
  }

  /* DefaultValue sits a fixed distance past PinCategory; find that distance by
     testing every candidate against all pins in the file. */
  function calibrateDefaultValue(nodes, pkg) {
    var best = { delta: -1, score: 0, tried: 0, nonEmpty: 0 };
    var minRef = -pkg.imports.length, maxRef = pkg.exports.length;
    /* A sample is as good as the whole file here, and keeps big assets fast. */
    var sample = [], budget = 1500;
    for (var s = 0; s < nodes.length && budget > 0; s++) {
      sample.push(nodes[s]);
      budget -= nodes[s].pins.length;
    }
    nodes = sample;
    for (var delta = 16; delta <= 320; delta++) {
      var valid = 0, tried = 0, nonEmpty = 0;
      for (var n = 0; n < nodes.length; n++) {
        var nd = nodes[n];
        for (var p = 0; p < nd.pins.length; p++) {
          var pin = nd.pins[p];
          if (pin.categoryAt == null) continue;
          tried++;
          var a = tryString(nd.view.dv, nd.view.u8, pin.categoryAt + delta, pin.segEnd, true);
          if (!a) continue;
          var b = tryString(nd.view.dv, nd.view.u8, a.end, pin.segEnd, true);
          if (!b) continue;
          /* DefaultObject follows both strings and must be a real package index;
             this is what separates the true offset from coincidental matches. */
          if (b.end + 4 > pin.segEnd) continue;
          var ref = nd.view.dv.getInt32(b.end, true);
          if (ref < minRef || ref > maxRef) continue;
          valid++;
          if (!a.empty) nonEmpty++;
        }
      }
      /* Only an offset that explains virtually every pin can be the real one. */
      var score = (tried && valid >= tried * 0.9) ? nonEmpty * 8 + valid : 0;
      if (score > best.score) {
        best = { delta: delta, score: score, tried: tried, nonEmpty: nonEmpty, valid: valid };
      }
    }
    return best;
  }

  /**
   * Extract every pin and connection in the package.
   * @param {Package} pkg
   * @param {Object} objects  index -> { export, props } produced by the model builder
   */
  UA.extractPins = function (pkg, objects) {
    var nodes = [];
    for (var i = 0; i < pkg.exports.length; i++) {
      var e = pkg.exports[i];
      if (!isNodeClass(e.className)) continue;
      var o = objects[i];
      if (!o || !o.props || o.props.trailingStart == null) continue;
      var start = o.props.trailingStart, end = o.props.trailingEnd;
      if (!(end > start)) continue;
      var view = {
        dv: new DataView(o.props.buffer), u8: new Uint8Array(o.props.buffer),
        start: start, end: end
      };
      var res = scanNodePins(pkg, view, e.packageIndex);
      nodes.push({ index: i, view: view, pins: res.pins, mode: res.mode });
    }

    var stats = { nodes: nodes.length, pins: 0, links: 0, mode: 'none', directionConfidence: 0 };
    if (!nodes.length) return { byNode: {}, stats: stats };

    /* Global pin table: guid -> owning node and pin slot. */
    var table = {};
    for (var n = 0; n < nodes.length; n++) {
      var nd = nodes[n];
      stats.pins += nd.pins.length;
      for (var p = 0; p < nd.pins.length; p++) {
        nd.pins[p].node = nd.index;
        nd.pins[p].slot = p;
        table[nd.index + '|' + nd.pins[p].guid] = nd.pins[p];
      }
    }

    var dir = calibrateDirection(nodes);
    stats.directionConfidence = dir.score;
    var def = calibrateDefaultValue(nodes, pkg);

    for (var m = 0; m < nodes.length; m++) {
      var node = nodes[m];
      for (var q = 0; q < node.pins.length; q++) {
        var pin = node.pins[q];
        if (pin.categoryAt == null) continue;
        if (dir.score > 0.9) {
          var at = pin.categoryAt + dir.off;
          if (at >= node.view.start) {
            pin.direction = dir.off === -1 ? node.view.u8[at] : node.view.dv.getInt32(at, true);
          }
        }
        if (def.delta > 0 && def.nonEmpty > 0) {
          var dvs = tryString(node.view.dv, node.view.u8, pin.categoryAt + def.delta, pin.segEnd, true);
          if (dvs && dvs.text) pin.defaultValue = dvs.text;
        }
      }
    }

    /* Connections: every (owner, guid) pair inside a pin's slice that resolves to
       a real pin owned by that node. Pairs pointing at the pin's own node are the
       parent/sub-pin relationships of a split struct pin, not connections. */
    for (var k = 0; k < nodes.length; k++) {
      var nk = nodes[k];
      for (var pi = 0; pi < nk.pins.length; pi++) {
        var cur = nk.pins[pi];
        var scanFrom = cur.categoryAt != null ? cur.categoryAt : cur.bodyAt;
        for (var a2 = scanFrom; a2 + 20 <= cur.segEnd; ) {
          var ref = nk.view.dv.getInt32(a2, true);
          if (ref > 0 && ref <= pkg.exports.length && looksLikeGuid(nk.view.u8, a2 + 4)) {
            var other = table[(ref - 1) + '|' + hexAt(nk.view.u8, a2 + 4)];
            if (other) {
              if (other.node === nk.index) {
                if (other !== cur && cur.subPinOf == null && other.slot < cur.slot) cur.subPinOf = other.slot;
              } else {
                cur.links.push({ node: other.node, slot: other.slot, guid: other.guid });
              }
              a2 += 20;
              continue;
            }
          }
          a2++;
        }
      }
    }

    /* Connections are stored on both ends but split sub-pins only record one
       side, so mirror every edge to get a complete picture. */
    var byNode = {};
    for (var z = 0; z < nodes.length; z++) byNode[nodes[z].index] = nodes[z];
    var seen = {};
    for (var y = 0; y < nodes.length; y++) {
      var ny = nodes[y];
      for (var yp = 0; yp < ny.pins.length; yp++) {
        var src = ny.pins[yp];
        for (var L = 0; L < src.links.length; L++) {
          var t = src.links[L];
          var target = byNode[t.node] && byNode[t.node].pins[t.slot];
          if (!target) continue;
          var ka = src.node + ':' + src.slot, kb = target.node + ':' + target.slot;
          seen[ka < kb ? ka + '|' + kb : kb + '|' + ka] = true;
          var mirrored = target.links.some(function (x) { return x.node === src.node && x.slot === src.slot; });
          if (!mirrored) target.links.push({ node: src.node, slot: src.slot, guid: src.guid });
        }
      }
    }
    stats.links = Object.keys(seen).length;
    var modeCount = {};
    nodes.forEach(function (nd) { if (nd.pins.length) modeCount[nd.mode] = (modeCount[nd.mode] || 0) + 1; });
    stats.mode = Object.keys(modeCount).sort(function (a, b) { return modeCount[b] - modeCount[a]; })[0] || 'none';
    return { byNode: byNode, stats: stats };
  };
})(typeof window !== 'undefined' ? window : globalThis);
